version: "3.9"
   
services:
  db_softdesk:
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${DB_PORT}
      
  api:
    image: softdesk_api
    build: ./api
    command: bash -c "pwd && python manage.py migrate && python manage.py runserver 0.0.0.0:${API_PORT}" 
    # command: bash -c "pwd && ls && python manage.py migrate && python manage.py runserver 0.0.0.0:${API_PORT}" 
    volumes:
      - ./api:/code
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_NAME=${POSTGRES_SERVICE_NAME}
      # - APP_NAME=Home
    depends_on:
      - db_softdesk
      # erreur mais je ne comprends pas laquelle 

  adminer:
    container_name: adminer_softdesk
    image: dockette/adminer
    ports:
      - ${ADMINER_PORT}:80


